name: Build and Package APK

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 更新到 v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3  # 更新到 v3
      with:
        distribution: 'adopt'
        java-version: '17'  # 更新到 Java 17

    - name: Build with Gradle
      run: |
        ./gradlew build -x detekt
        ./gradlew build -Pandroid.lint.ignoreErrors=true
      continue-on-error: true  # 继续执行即使构建失败

    - name: Package APK
      run: ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3  # 更新到 v3
      with:
        name: app-release
        path: app/build/outputs/apk/release/*.apk
